sudo: false
language: node_js
node_js:
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"

deploy:
  provider: npm
  email:
    secure: "e7h3bSCpc7Vw4g7Bwn/qaQuas8QfmpXETQ3q091B7uNjkdMXPSHi2TvHDeBwRHOEsmrYxj8hhjAXnU6jI0sToPv3Q7r4MO3nPPcD2TKbanRxwi/7w6qdyu51lIGlkqLv0ueRo+S+ANCrAFy9SaPbXU4GqM1narP2NLZVJ10w0jB9bzULImKOSavofcnGTZyVnkTmZhKcpiSI5wwtE3ab0bVGIKgalsMuxUN2lPngumdL5pz3j2f0Ctjp1mKeY5EjUXiWc5l/Z4S85X/QdOpjKUPrf5bp+TkY3UCSxXut7nUpckgm7++qezzod6X2MhBMb8g2Cha9s/SmkgeGcv0iJCAS/CsCAhXui8YNguc5UOnRHemsD4zOo8ixV6Y7Yr6/GVhd09qyOk6KzBFFVMoFQm7Q9GwhCfusK794wXd6ACJbUgvmZWF7sHYriYMoXx2SgpG1CK8RFPUGA2Wx5xxNFDYBgvRXuUzlJW+rpZEl2UFk6fRg8SM1jlJiqoEp6vZWZE6FVZHnum+Lj0GbELnvU3B/LsujdwWVElKKvHBkIBNWGHJkMjHYRSa1w/0H4iPAkrfVtSjZGrCQPMplEx0gcDqttvDIcu/p+enBt9XdER/8YM4yISLcYZlJczlyFf8+SNWYtbqpdIFwX/tGJ5fMzb/0zu7Z3nsLP1ZfUrnHM24="
  api_key: 
    secure: "DhTqVGno/1eq1HN1tjo53cyDGYbFOYUFPAOMcxSzl08ZSSgaVPctyG+/2uXyABNmJFqk8+OmIUCMBJJKWUFNg5hbAuZ4WUYAKj3B2mPVciWhx2kgHv0t/mwzPEuav1Sv3qofd126pcWwKabMgUQUuERiYXil5ek5uml2sJc3ZnHG9JaqiKHe3RqXnf9LFiTwrK40RQvT6V1+1/bSw6EDNgGlYseijuA3Za1rkn8DiJ4exzkLACu2WUFLvXSjiPyIax25bG7JJ8crqQHLGQVOh7wmsJZw0u5UQPuKm5G+3WLne+MgIdzH+BLh3IHzZ/q6Y2geYianTB9mX3ilrG0H7xHBsb4vl/ZTG1qPalSKF0sjMZbCWn4pv/lMYbaZExrq+hAiwfiSqmbs4mxCPJegyynFpMNvkImX6MyDtT7VsLpFQK1OKldPulIQ0DSh8ybFf12M9x1voCs8ZJKDPpBJEzisFeLEr6XWJpHcjBdxupWkJ/ocwy6IJD2u5mSJfuD337aS2TQg8LMY6jrwQlp5Pt2dDpVrXhw3/l4YvmdJoDjfquU1z2GUTkXks9hqo4HPXwAP8eA/xonc1d3Wtmg1YQ3IQVpnQZnhmX4D2h6OIwD1K2eOiF9QA+JQKvXzY6HOlE3BuVk+UN8uNGaosbAcLRPnD5FU9fD07Cm0h0S3b5U="
  on:
    tags: true
    branch: master
